from macpep_scylladb.models.Trypsin import Trypsin
from macpep_scylladb.modules.Proteomics import Proteomics

expected = {
    "VTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSRNVIQISNDLENLRDLLHLLAASK",
    "NVIQISNDLENLRDLLHLLAASKSCPLPQVRALESLESLGVVLEASLYSTEVVALSR",
    "DLLHLLAASKSCPLPQVRALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLR",
    "QRVTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSRNVIQISNDLENLR",
    "INDISHTQSVSSKQRVTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSR",
    "SCPLPQVRALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLRQLDLSPGC",
    "MDQTLAIYQQILASLPSRNVIQISNDLENLRDLLHLLAASKSCPLPQVR",
    "VTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSRNVIQISNDLENLR",
    "SCPLPQVRALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLR",
    "ALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLRQLDLSPGC",
    "DLLHLLAASKSCPLPQVRALESLESLGVVLEASLYSTEVVALSR",
    "MDQTLAIYQQILASLPSRNVIQISNDLENLRDLLHLLAASK",
    "QRVTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSR",
    "TIVTRINDISHTQSVSSKQRVTGLDFIPGLHPLLSLSK",
    "VTGLDFIPGLHPLLSLSKMDQTLAIYQQILASLPSR",
    "ALESLESLGVVLEASLYSTEVVALSRLQGSLQDMLR",
    "CGPLYRFLWLWPYLSYVEAVPIRKVQDDTK",
    "SCPLPQVRALESLESLGVVLEASLYSTEVVALSR",
    "INDISHTQSVSSKQRVTGLDFIPGLHPLLSLSK",
    "MDQTLAIYQQILASLPSRNVIQISNDLENLR",
    "NVIQISNDLENLRDLLHLLAASKSCPLPQVR",
    "FLWLWPYLSYVEAVPIRKVQDDTKTLIK",
    "MRCGPLYRFLWLWPYLSYVEAVPIRK",
    "MRCGPLYRFLWLWPYLSYVEAVPIR",
    "VQDDTKTLIKTIVTRINDISHTQSVSSK",
    "CGPLYRFLWLWPYLSYVEAVPIRK",
    "FLWLWPYLSYVEAVPIRKVQDDTK",
    "CGPLYRFLWLWPYLSYVEAVPIR",
    "ALESLESLGVVLEASLYSTEVVALSR",
    "TLIKTIVTRINDISHTQSVSSKQR",
    "NVIQISNDLENLRDLLHLLAASK",
    "TLIKTIVTRINDISHTQSVSSK",
    "FLWLWPYLSYVEAVPIRK",
    "TIVTRINDISHTQSVSSKQR",
    "QRVTGLDFIPGLHPLLSLSK",
    "FLWLWPYLSYVEAVPIR",
    "MDQTLAIYQQILASLPSR",
    "TIVTRINDISHTQSVSSK",
    "LQGSLQDMLRQLDLSPGC",
    "DLLHLLAASKSCPLPQVR",
    "VTGLDFIPGLHPLLSLSK",
    "KVQDDTKTLIKTIVTR",
    "VQDDTKTLIKTIVTR",
    "INDISHTQSVSSKQR",
    "NVIQISNDLENLR",
    "INDISHTQSVSSK",
    "KVQDDTKTLIK",
    "VQDDTKTLIK",
    "LQGSLQDMLR",
    "DLLHLLAASK",
    "TLIKTIVTR",
    "MRCGPLYR",
    "SCPLPQVR",
    "KVQDDTK",
    "QLDLSPGC",
    "CGPLYR",
    "VQDDTK",
    "TIVTR",
    "TLIK",
    "MR",
    "QR",
    "K",
}


def test_digest():
    sequence = (
        "MRCGPLYRFLWLWPYLSYVEAVPIRKVQDDTKTLIKTIVTRINDISHTQSVSSKQRVTGLDFIPGLHP"
        "LLSLSKMDQTLAIYQQILASLPSRNVIQISNDLENLRDLLHLLAASKSCPLPQVRALESLESLGVVLE"
        "ASLYSTEVVALSRLQGSLQDMLRQLDLSPGC"
    )
    trypsin = Trypsin(
        max_number_of_missed_cleavages=3,
        minimum_peptide_length=0,
        maximum_peptide_length=60,
    )
    proteomics = Proteomics()
    peptide_list = proteomics.digest(sequence, trypsin)

    assert len(expected) == len(peptide_list)

    for peptide in expected:
        assert peptide in peptide_list
