version: "3"
networks:
  scylla:


services:
  node1:
    image: scylladb/scylla
    container_name: node1
    command: "--api-address 0.0.0.0"
    ports:
      - 9042:9042
    networks:
      - scylla

  node2:
    image: scylladb/scylla
    container_name: node2
    command: "--api-address 0.0.0.0"
    ports:
      - 9043:9042
    networks:
      - scylla

  node3:
    image: scylladb/scylla
    container_name: node3
    command: "--api-address 0.0.0.0"
    ports:
      - 9044:9042
    networks:
      - scylla
