version: "3"
services:
  node1:
    image: scylladb/scylla
    ports:
      - "9042:9042"
    restart: always
    command: --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
  node2:
    image: scylladb/scylla
    restart: always
    command: --seeds=node1 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
  node3:
    image: scylladb/scylla
    restart: always
    command: --seeds=node1 --smp 1 --memory 750M --overprovisioned 1 --api-address 0.0.0.0
    networks:
      - scylla-net
  app:
    build: .
    command: tail -f /dev/null
    networks:
      - scylla-net
    volumes:
      - .:/app

networks:
  scylla-net:
    driver: bridge
